# Generated by Django 2.2.4 on 2020-06-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete_product_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('reason_for_removal', models.TextField(default='')),
                ('supplier_username', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
       
    ]
