# Generated by Django 2.2.4 on 2020-06-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200607_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
