# Generated by Django 3.0.4 on 2020-06-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200607_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='society',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Society'),
        ),
    ]
