# Generated by Django 2.2.4 on 2020-06-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200613_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='orders_placed',
            field=models.IntegerField(default=0),
        ),
    ]
