# Generated by Django 2.2.4 on 2020-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='corporate_discount',
            field=models.IntegerField(default=0),
        ),
    ]
