# Generated by Django 2.2.4 on 2020-06-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
